blank_issues_enabled: false
contact_links:
  - name: GitHub Discussions
    url: https://github.com/joadoumie/NBACmdPalExtension/discussions
    about: Ask questions and discuss ideas with the community
